---
- name: roles/389ds/main.yml
  set_fact: dummy=0

# 389-ds-base{,-libs}, cockpit-389-ds will be installed
- name: Install 389-directory-server
  command: dnf module install -y 389-directory-server:stable/default
  args:
    warn: no
  become: yes

- name: Check if LDAP instance has already been deployed
  command: dsconf localhost backend suffix list
  become: yes
  register: dsconf
  ignore_errors: yes

# - debug: var=dsconf 

- name: Deploy template for 389-ds
  template:
    src: 389-template
    dest: /tmp/
  when: dsconf.failed

- name: Install initial instance
  command: dscreate from-file /tmp/389-template
  become: yes
  when: dsconf.failed

- name: Grant Access of firewalld(LDAP)
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    service: ldap
  become: yes
  with_items: "{{ DB_DEV_CIDR }}"

- name: Grant Access of firewalld(cockpit)
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    service: cockpit
  become: yes
  with_items: "{{ DB_DEV_CIDR }}"
  when: ENABLE_COCKPIT

- name: Apply changes of firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
  become: yes

- name: Cockpit Web UI start
  systemd:
    name: cockpit
    state: restarted
    enabled: yes
  become: yes
  when: ENABLE_COCKPIT

- import_tasks: sssd.yml
  when: ENABLE_SSSD_LDAP
  tags: sssd
