---
- name: roles/nginx/tasks/main.yml
  command: echo

- name: Install nginx for CentOS {{ _V }}.x
  yum: 
    name:
      - nginx-all-modules
      - python3-certbot-nginx
  become: yes

- name: nginx - Add common settings
  copy:
    dest: /etc/nginx/conf.d/
    src:  http_common.conf
  become: yes
  notify: restart nginx

- name: Grant Access from development client
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    rich_rule: 'rule family=ipv4 service name="http" source address="{{ item }}" accept'
  become: yes
  with_items: "{{ DB_DEV_CIDR }}"
  notify: restart firewalld
  when: ENABLE_FIREWALLD
