---
- name: roles/services/handlers/main.yml
  command: echo

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
  become: yes

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  become: yes

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes
  become: yes

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
