---
- name: roles/samba4/tasks/core.yml
  set_fact: dummy=0

- name: Install samba packages
  dnf:
    name:
      - centos-release-samba413
      - samba
      - samba-client
      - samba-test
      - python3-samba-test
      - samba-winbind
      - samba-winbind-clients
      - samba-winbind-krb5-locator
      - ipa-client-samba
      - samba-pidl
  become: yes

- name: Add SMB_FQDN entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regex: ^{{ SMB_IP }} +{{ SMB_HOSTNAME }} +{{ SMB_FQDN }}
    line: "{{ SMB_IP }} {{ SMB_HOSTNAME }} {{ SMB_FQDN }}"
  become: yes

# - debug: var=SMB_IP

# https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html
- name: Change DNS for SMB
  nmcli:
    conn_name: "{{ SMB_CON }}"
    ip4: "{{ SMB_IP }}"
    dns4: "{{ SMB_DNS }}"
    state: present
    type: ethernet
  become: yes

- name: Deploy /etc/samba/smb.conf
  template:
    src: smb.conf
    dest: /etc/samba/
  become: yes

- name: Restart samba to apply change
  systemd:
    name: smb
    state: restarted
    enabled: yes
  become: yes
