# Set locale
---
- name: roles/base/tasks/locale.yml
  set_fact: dummy=0

- name: Get locale data
  dnf:
    name: glibc-langpack-ja
  become: yes

- name: Set Locale to ja_JP.utf8
  command: localectl set-locale LANG=ja_JP.utf8
  become: yes
