# Basic Congiguration Control
---
- name: roles/base/tasks/main.yml
  set_fact: dummy=0

- name: Enable fastest mirror
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^fastestmirror
    line: fastestmirror=true
  become: yes

- import_tasks: stream.yml
  when: ENABLE_STREAM
- import_tasks: powertools.yml
- import_tasks: phprepo.yml
- import_tasks: mandatory.yml
- import_tasks: prompt.yml
- import_tasks: users.yml
- import_tasks: security.yml
- import_tasks: time.yml
- import_tasks: locale.yml
