---
- name: roles/base/tasks/mandatory.yml
  set_fact: dummy=0

- name: Install tools 
  dnf: 
    enablerepo: PowerTools
    name:
      - chrony
      - glibc-devel
      - gcc-c++
      - git
      - patch
      - rsync
      - vim-enhanced
      - nkf
      - bind-utils
      - unzip
      - bzip2
      - wget
      - w3m
      - kernel-devel
      - man
      - npm
  become: yes

- name: Prepare directory for WWW_BASE
  file:
    path:     "{{ WWW_BASE }}"
    state:    directory
    owner:    "{{ ansible_user_id }}"
  become: yes
