---
- name: roles/base/tasks/security.yml
  set_fact: dummy=0

- name: Install tools required for disabling selinux
  dnf: 
    name: 
      - python3-libselinux
    state: present
  become: yes

- name: Disable selinux 
  selinux:
    state: disabled
  become: yes

- name: Enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes
